database:
  path: securevault.db
  backup_interval: 24  # hours
detection:
  ml_model_path: models/classifier.pkl
  sensitivity_threshold: 0.8
  rate_limit: 100  # files per minute
  batch_size: 10
logging:
  file_path: logs/securevault.log
  level: INFO
  rotation: 7  # days
monitoring:
  clipboard_check_interval: 1
  file_patterns:
  - '*.doc'
  - '*.docx'
  - '*.pdf'
  - '*.txt'
  - '*.xlsx'
  - '*.csv'
  screenshot_interval: 5
  queue_size: 1000
  priority_extensions:
  - '.pdf'
  - '.docx'
